name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # This allows manual triggers
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Prepare Python Script
      run: |
        python createResourceGroup.py
        python jsl_git_get_first_commit.py

    - name: Execute Python Script
      run: |
        chmod +x createResourceGroup.py
        python createResourceGroup.py

    - name: Generate Release Change Log
      run: |
        first_commit=$(python -c 'from jsl_git_get_first_commit import jsl_git_get_first_commit; print(jsl_git_get_first_commit())')
        echo "First commit hash: $first_commit"
